simplified tcl install in conda-windows

diff --git a/.github/workflows/test_pip_tcl_macos.yml b/.github/workflows/test_pip_tcl_macos.yml
--- a/.github/workflows/test_pip_tcl_macos.yml
+++ b/.github/workflows/test_pip_tcl_macos.yml
@@ -47,43 +47,57 @@ jobs:
         repository: tcltk/tcl
         ref: core-8-5-branch
         path: tcl
-    - name: Prepare checked out repository
+
+    # Install acc to the 8-5-branch workflow   
+    # - name: Prepare checked out repository
+    #   run: |
+    #     touch ../generic/tkStubInit.c ../doc/man.macros
+    #     mkdir "$HOME/install"
+    #   working-directory: tk/unix
+    # - name: Add Tcl
+    #   run: |
+    #     brew install tcl-tk
+    # - name: Add X11
+    #   run: |
+    #     brew install --cask xquartz
+    #     sudo /opt/X11/libexec/privileged_startx || true
+    # - name: Configure (symbols=${{ matrix.symbols }} ${{matrix.options }})
+    #   # Note that macOS is always a 64 bit platform
+    #   run: |
+    #     ./configure --enable-64bit --enable-framework --disable-xft --with-tcl=/usr/local/opt/tcl-tk/lib --x-includes=/opt/X11/include --x-libraries=/opt/X11/lib CFLAGS=-I/usr/local/opt/tcl-tk/include ${CFGOPT} "--prefix=$HOME/install" || {
+    #       cat config.log
+    #       echo "::error::Failure during Configure"
+    #       exit 1
+    #     }
+    #   working-directory: tk/unix
+    #   env:
+    #     CFGOPT: --enable-symbols=${{ matrix.symbols }} ${{matrix.options }}
+    # - name: Build
+    #   run: |
+    #     make binaries libraries tktest || {
+    #       echo "::error::Failure during Build"
+    #       exit 1
+    #     }
+    #   working-directory: tk/unix
+    # - name: Install
+    #   run: |
+    #     sudo make install || {
+    #       echo "::error::Failure during Install"
+    #       exit 1
+    #     }
+    #   working-directory: tk/unix
+
+
+    - name: Install acc to 8-5-branch README
       run: |
-        touch ../generic/tkStubInit.c ../doc/man.macros
-        mkdir "$HOME/install"
-      working-directory: tk/unix
-    - name: Add Tcl
-      run: |
-        brew install tcl-tk
-    - name: Add X11
-      run: |
-        brew install --cask xquartz
-        sudo /opt/X11/libexec/privileged_startx || true
-    - name: Configure (symbols=${{ matrix.symbols }} ${{matrix.options }})
-      # Note that macOS is always a 64 bit platform
-      run: |
-        ./configure --enable-64bit --enable-framework --disable-xft --with-tcl=/usr/local/opt/tcl-tk/lib --x-includes=/opt/X11/include --x-libraries=/opt/X11/lib CFLAGS=-I/usr/local/opt/tcl-tk/include ${CFGOPT} "--prefix=$HOME/install" || {
-          cat config.log
-          echo "::error::Failure during Configure"
-          exit 1
-        }
-      working-directory: tk/unix
-      env:
-        CFGOPT: --enable-symbols=${{ matrix.symbols }} ${{matrix.options }}
-    - name: Build
-      run: |
-        make binaries libraries tktest || {
-          echo "::error::Failure during Build"
-          exit 1
-        }
-      working-directory: tk/unix
-    - name: Install
-      run: |
-        sudo make install || {
-          echo "::error::Failure during Install"
-          exit 1
-        }
-      working-directory: tk/unix
+        ver=""
+        CFLAGS="-arch i386 -arch x86_64 -arch ppc -mmacosx-version-min=10.5"
+        export CFLAGS
+        make -C tcl${ver}/macosx
+        make -C tk${ver}/macosx
+        sudo make -C tcl${ver}/macosx install
+        sudo make -C tk${ver}/macosx  install
+      working-directory: "."
 
 
 
